version: 0.2

phases:
  pre_build:
    commands:
      - npm install --force
  build:
    commands:
      - npm run build
      
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build